development:
  adapter: postgresql
  encoding: unicode
  database: gol_development
  host: localhost
  pool: 5
  username: db_user
  password: db_password

test:
  adapter: postgresql
  encoding: unicode
  database: gol_test
  host: localhost
  pool: 5
  username: db_user
  password: db_password
